version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_unchess
    env_file:
      - .env.local
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - db_network

volumes:
  pg_data:

networks:
  db_network:

